In [1]:
import tensorflow as tf

In [2]:
#creating variables in Tensorflow
#Tensor refers to array
tf.__version__

'1.10.0'

In [3]:
hello=tf.constant("Hello")

In [4]:
hello #you cannot see the value of HELLO directly,
#It will show you the datatype it's shape and Const

<tf.Tensor 'Const:0' shape=() dtype=string>

In [5]:
hello

<tf.Tensor 'Const:0' shape=() dtype=string>

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [7]:
world=tf.constant("World")

In [8]:
world

<tf.Tensor 'Const_1:0' shape=() dtype=string>

In [9]:
var2=tf.constant("This is second variable: ")

In [10]:
var2 #in the outpput Const_2:0 refers to total numbers of constants 

<tf.Tensor 'Const_2:0' shape=() dtype=string>

In [11]:
#To Display the variable value we can use Sessions
with tf.Session() as s:
    x=s.run(var2) #s.run() runs operations and evaluates tensors

In [12]:
x 

b'This is second variable: '

In [13]:
print(x)

b'This is second variable: '


In [14]:
var2

<tf.Tensor 'Const_2:0' shape=() dtype=string>

In [15]:
var3=tf.constant("This is the third variable")

In [16]:
var3

<tf.Tensor 'Const_3:0' shape=() dtype=string>

In [17]:
print(var3)

Tensor("Const_3:0", shape=(), dtype=string)


In [18]:
int_val=tf.constant(100)

In [19]:
int_val

<tf.Tensor 'Const_4:0' shape=() dtype=int32>

In [20]:
#concatenating 2 strings
with tf.Session() as s:
    concat=s.run(var2+var3)

In [21]:
concat 

b'This is second variable: This is the third variable'

#  Creating Matrix in Tensorflow

In [25]:
#anonther why to Display values
sess=tf.InteractiveSession()

/home/usman/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py:1645: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [23]:
mat1=tf.fill((5,5),10)

In [24]:
mat1

<tf.Tensor 'Fill:0' shape=(5, 5) dtype=int32>

In [26]:
sess.run(mat1)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]], dtype=int32)

In [27]:
mat2=tf.fill((10,),20)

In [28]:
mat2

<tf.Tensor 'Fill_1:0' shape=(10,) dtype=int32>

In [29]:
sess.run(mat2)

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20], dtype=int32)

In [30]:
zeros=tf.zeros((4,5))

In [31]:
zeros

<tf.Tensor 'zeros:0' shape=(4, 5) dtype=float32>

In [32]:
sess.run(zeros)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)

In [33]:
mat1/3

<tf.Tensor 'truediv:0' shape=(5, 5) dtype=float64>

In [34]:
sess.run(mat1)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]], dtype=int32)

In [35]:
sess.run(mat1/4)

array([[2.5, 2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5, 2.5]])

In [36]:
mat3=tf.fill((10,10),2.4)

In [37]:
mat3

<tf.Tensor 'Fill_2:0' shape=(10, 10) dtype=float32>

In [39]:
answer=tf.matmul(mat3,mat3*10) #performs matrix multiplication. datatype should also be same

In [40]:
answer

<tf.Tensor 'MatMul_1:0' shape=(10, 10) dtype=float32>

In [41]:
sess.run(answer)

array([[576., 576., 576., 576., 576., 576., 576., 576., 576., 576.],
       [576., 576., 576., 576., 576., 576., 576., 576., 576., 576.],
       [576., 576., 576., 576., 576., 576., 576., 576., 576., 576.],
       [576., 576., 576., 576., 576., 576., 576., 576., 576., 576.],
       [576., 576., 576., 576., 576., 576., 576., 576., 576., 576.],
       [576., 576., 576., 576., 576., 576., 576., 576., 576., 576.],
       [576., 576., 576., 576., 576., 576., 576., 576., 576., 576.],
       [576., 576., 576., 576., 576., 576., 576., 576., 576., 576.],
       [576., 576., 576., 576., 576., 576., 576., 576., 576., 576.],
       [576., 576., 576., 576., 576., 576., 576., 576., 576., 576.]],
      dtype=float32)

# RandomNumber generation in TensorFlow

In [44]:
rand=tf.random_normal((5,6)) #creates a Matrix of a random number

In [45]:
rand

<tf.Tensor 'random_normal_2:0' shape=(5, 6) dtype=float32>

In [46]:
sess.run(rand)

array([[-0.15784806, -0.61160886, -0.4685305 , -1.9576907 , -1.200842  ,
         0.06652173],
       [-1.2035309 , -0.6444691 ,  0.23936404, -0.0974737 ,  0.20125927,
        -0.08373615],
       [-0.3272949 ,  2.2062073 , -0.24354406, -0.8258624 ,  0.4312988 ,
         1.0882134 ],
       [-0.761334  , -0.7348588 , -0.35281715,  0.1227803 ,  0.11556355,
        -1.0799938 ],
       [ 1.7095124 ,  0.10896864,  1.3456497 , -1.7409024 , -1.1843776 ,
         0.23249733]], dtype=float32)

In [47]:
rand2=tf.random_normal((4,4),mean=0,stddev=1) #you can also apply  standard Deviation and mean 

In [48]:
sess.run(rand2)

array([[ 0.3226118 , -0.5627434 ,  1.1867425 ,  1.4755472 ],
       [ 0.38959485, -1.4454757 ,  2.3510509 , -0.75329196],
       [ 1.3008372 ,  0.5780922 ,  1.829373  , -1.82492   ],
       [ 0.9592204 ,  0.32822353,  0.44209632, -0.8514416 ]],
      dtype=float32)

In [57]:
rufm=tf.random_uniform((4,5),minval=10,maxval=32)

In [58]:
rufm

<tf.Tensor 'random_uniform_2:0' shape=(4, 5) dtype=float32>

In [59]:
sess.run(rufm)

array([[19.319996 , 15.159631 , 21.445848 , 12.674721 , 18.067766 ],
       [21.20116  , 13.137177 , 30.42254  , 28.270784 , 17.9459   ],
       [30.400726 , 31.249125 , 24.951828 , 19.912193 , 13.813676 ],
       [20.842571 , 10.2008705, 19.810196 , 18.170092 , 26.550592 ]],
      dtype=float32)

In [61]:
#you can also creates matrix like this
cmat=tf.constant([[1,2,3],[6,2,5]])

In [63]:
cmat

<tf.Tensor 'Const_5:0' shape=(2, 3) dtype=int32>

In [62]:
sess.run(cmat)

array([[1, 2, 3],
       [6, 2, 5]], dtype=int32)