In [38]:
import tensorflow as tf

# Variables in TENSORFLOW

In [39]:
sess=tf.InteractiveSession()

/home/usman/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py:1645: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [40]:
my_tensor=tf.random_uniform((5,5),0,2)

In [41]:
sess.run(my_tensor)

array([[0.49551678, 1.9421365 , 1.5890675 , 0.7460253 , 1.6064987 ],
       [0.31066608, 0.20280194, 1.7323632 , 0.29397273, 1.6007297 ],
       [1.0875027 , 0.7713363 , 0.9387789 , 1.407418  , 0.5366607 ],
       [0.26340413, 1.6772883 , 1.9472029 , 0.7514138 , 0.6819515 ],
       [0.946532  , 0.78942466, 1.2565627 , 0.1864934 , 0.16427326]],
      dtype=float32)

In [42]:
var1=tf.Variable(initial_value=my_tensor)

In [43]:
var1

<tf.Variable 'Variable_3:0' shape=(5, 5) dtype=float32_ref>

In [44]:
print(var1) #output is now tf.Variable instead of tf.tensor

<tf.Variable 'Variable_3:0' shape=(5, 5) dtype=float32_ref>


In [45]:
#sess.run(var1) 
#right now it will give you can error, bc it is not initialized

In [46]:
init=tf.global_variables_initializer() #initializing all variable

In [47]:
sess.run(init)

In [48]:
sess.run(var1)

array([[0.43913937, 0.3498659 , 1.7660112 , 1.1369097 , 1.4887326 ],
       [0.5865216 , 1.2246263 , 1.0999465 , 0.86417675, 1.9243574 ],
       [1.4113936 , 0.09077215, 1.984833  , 0.41194677, 0.99064445],
       [0.5975919 , 0.231215  , 1.2243526 , 1.9903514 , 0.23051047],
       [1.5489504 , 1.0079694 , 1.6475811 , 1.5640495 , 1.5690804 ]],
      dtype=float32)

In [50]:
#creating another variable
tensor2=tf.random_normal((5,4),3,32)

In [51]:
tensor2

<tf.Tensor 'random_normal_1:0' shape=(5, 4) dtype=float32>

In [52]:
sess.run(tensor2)

array([[ 18.951889 , -32.77548  , -35.887543 ,   2.084158 ],
       [-53.603153 , -15.002649 , -10.085814 , -43.750126 ],
       [  3.988996 ,  -0.8579705,   2.798193 , -16.971773 ],
       [ -5.113778 ,  -6.7964087, -30.92294  , -35.613243 ],
       [ -3.896122 ,  -7.676177 , -27.237257 ,  53.11218  ]],
      dtype=float32)

In [53]:
var2=tf.Variable(initial_value=tensor2)

In [54]:
var2

<tf.Variable 'Variable_4:0' shape=(5, 4) dtype=float32_ref>

In [56]:
x=tf.global_variables_initializer()

In [58]:
sess.run(x)  #running this is necessary

In [59]:
sess.run(var2)

array([[ -7.611438 ,   7.748625 , -36.234447 , -23.014072 ],
       [ 20.305197 , -16.389437 , -19.933487 ,  -8.256302 ],
       [-29.15524  ,  19.546196 , -57.19261  ,  26.9353   ],
       [-18.067774 , -18.801615 ,  13.378944 ,  -4.6055403],
       [-12.654668 ,  44.424458 ,  -8.123372 ,  -3.8374882]],
      dtype=float32)

In [82]:
tensor3=tf.constant("This is a tensor")

In [83]:
tensor3

<tf.Tensor 'Const_1:0' shape=() dtype=string>

In [84]:
sess.run(tensor3)

b'This is a tensor'

In [85]:
#converting into variable
var3=tf.Variable(initial_value=tensor3)

In [86]:
var3

<tf.Variable 'Variable_6:0' shape=() dtype=string_ref>

In [87]:
xvar3=tf.global_variables_initializer()

In [88]:
sess.run(xvar3)

In [89]:
sess.run(var3)

b'This is a tensor'

In [90]:
sess.run(var3)

b'This is a tensor'

In [91]:
var3="This is avariable now"

In [95]:
print(var3)

This is avariable now


In [49]:
ph=tf.placeholder(tf.float32) #placeholder is a type of an enpty variable

In [14]:
ph

<tf.Tensor 'Placeholder:0' shape=<unknown> dtype=float32>

In [16]:
ph2=tf.placeholder(tf.int32,shape=(4,4))

In [17]:
ph3=tf.placeholder(tf.int32,shape=(None,4))

In [21]:
print(ph2,ph3,sep='\n')

Tensor("Placeholder_1:0", shape=(4, 4), dtype=int32)
Tensor("Placeholder_2:0", shape=(?, 4), dtype=int32)
